### ISSUE TITLE
test.py wont run

### ISSUE THREAD

**Issue by rsingh2083** [WuJie1010/TSP-PRL#2]
```
python2.7 test.py 
1334 test videos are readed
Traceback (most recent call last):
  File "test.py", line 34, in <module>
    test_dataset = Charades_Test_dataset()
  File "/media/test/ssd_ntfs/video_analytics_projects/TSP-PRL/dataloader_charades.py", line 215, in __init__
    with open(self.test_swin_txt_path) as f:
IOError: [Errno 2] No such file or directory: './Dataset/Charades/ref_info/charades_sta_test_swin_props_num_36364.txt'
```

**Comment by zyyworktable** [comment]
Hi . I found the missing files at his other github project"https://github.com/WuJie1010/Temporally-language-grounding',in the file "ref-info.tar'
